# Generated by Django 4.2.13 on 2024-05-26 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_owner",
                to="user.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_owner",
                to="user.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense_category",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_owner",
                to="user.user",
            ),
            preserve_default=False,
        ),
    ]
