# Generated by Django 4.2.13 on 2024-06-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="is_deleted",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
